workflows:
  ios_ipa_unsigned:
    name: iOS — Unsigned IPA (FX LIVE)
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Setup
        script: |
          set -e
          flutter create .
          flutter pub get
      - name: iOS permissions
        script: |
          set -e
          INFO_PLIST="ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Add :NSPhotoLibraryUsageDescription string This app may access the photo library." "$INFO_PLIST" ||           /usr/libexec/PlistBuddy -c "Set :NSPhotoLibraryUsageDescription This app may access the photo library." "$INFO_PLIST"
      - name: Build
        script: |
          set -e
          flutter build ipa --release --no-codesign --build-name=1.3.0 --build-number=$(date +%Y%m%d%H%M)
      - name: Collect artifacts
        script: |
          set -e
          mkdir -p artifacts
          if compgen -G "build/ios/ipa/*.ipa" > /dev/null; then
            cp build/ios/ipa/*.ipa artifacts/
          else
            APP_PATH="$(find build/ios -type d -name '*.app' | head -n 1 || true)"
            if [ -n "$APP_PATH" ]; then
              TMPDIR="$CM_BUILD_DIR/tmp_payload"
              rm -rf "$TMPDIR"; mkdir -p "$TMPDIR/Payload"
              cp -R "$APP_PATH" "$TMPDIR/Payload/Runner.app"
              (cd "$TMPDIR" && zip -r "$CM_BUILD_DIR/artifacts/MDA.ipa" Payload)
            fi
          fi
          ls -la artifacts || true
    artifacts:
      - artifacts/*.ipa

  android_release:
    name: Android — Release APK (FX LIVE)
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Build
        script: |
          set -e
          flutter create .
          flutter pub get
          flutter build apk --release --build-name=1.3.0 --build-number=$(date +%Y%m%d%H%M)
    artifacts:
      - build/app/outputs/**/*.apk
