name: mda_fx_live
description: MDA — LIVE Forex (WS) + CSV + Image Analysis (no subscription)
publish_to: "none"
version: 1.3.0+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  web_socket_channel: ^2.4.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/ohlc_sample.csv
